import streamlit as st
from utils.claude_client import get_claude_response, is_api_configured
from utils.prompts import EXAM_CATEGORIES, GOTCHA_TOPICS, SYSTEM_PROMPT_GOTCHA

st.set_page_config(page_title="Gotcha Topics", page_icon="🎯", layout="wide")

with st.sidebar:
    if is_api_configured():
        st.success("🔑 API Connected")
    else:
        st.warning("⚠️ API Key Missing")

    st.header("Select Category")
    category = st.selectbox("Category", EXAM_CATEGORIES, label_visibility="collapsed")

st.title("🎯 Gotcha Topics")
st.markdown(f"**Category:** {category}")
st.markdown("These are the concepts most likely to trip you up. Click any topic for a Claude explanation.")

st.divider()

topics = GOTCHA_TOPICS.get(category, [])

def render_topic(topic, btn_prefix, idx):
    short_key = f"short_{btn_prefix}_{idx}"
    detail_key = f"detail_{btn_prefix}_{idx}"

    col1, col2, col3 = st.columns([3, 1, 1])
    with col1:
        if short_key not in st.session_state:
            if st.button("Explain", key=f"btn_short_{btn_prefix}_{idx}"):
                with st.spinner("..."):
                    prompt = (
                        f"For this CCA-F exam gotcha, give a crisp 2–3 line answer covering:\n"
                        f"- The trap: what candidates do wrong\n"
                        f"- Use when: when the correct approach applies\n"
                        f"- Avoid when: when it backfires\n"
                        f"No preamble. Be blunt.\n\nGotcha: {topic}"
                    )
                    st.session_state[short_key] = get_claude_response(prompt, system_prompt=SYSTEM_PROMPT_GOTCHA)
                    st.rerun()

    if short_key in st.session_state:
        st.markdown(st.session_state[short_key])

        if detail_key not in st.session_state:
            if st.button("More Details", key=f"btn_detail_{btn_prefix}_{idx}", type="secondary"):
                with st.spinner("Generating full explanation..."):
                    prompt = (
                        f"Explain this gotcha in depth for the CCA-F exam. Structure your answer:\n"
                        f"**The Trap** — what candidates assume and why it seems reasonable\n"
                        f"**Use when** — the correct approach and when to apply it\n"
                        f"**Avoid when** — the exact conditions where the wrong choice bites you\n"
                        f"**Production scenario** — a concrete real-world example showing the mistake vs the correct decision\n"
                        f"**Exam signal** — the wording or context in a question that tells you which answer to pick\n\n"
                        f"Gotcha: {topic}"
                    )
                    st.session_state[detail_key] = get_claude_response(prompt, system_prompt=SYSTEM_PROMPT_GOTCHA)
                    st.rerun()
        else:
            st.markdown(st.session_state[detail_key])


for i, topic in enumerate(topics):
    with st.expander(f"**{i+1}.** {topic}"):
        render_topic(topic, category, i)

# Extra gotchas generated by Claude
extra_key = f"extra_gotchas_{category}"
if extra_key in st.session_state:
    for j, topic in enumerate(st.session_state[extra_key]):
        idx = len(topics) + j
        with st.expander(f"**{idx+1}.** {topic}"):
            render_topic(topic, f"extra_{category}", j)

st.divider()

if st.button("🔄 Get More Gotchas", key=f"more_{category}", type="secondary"):
    existing = topics + st.session_state.get(extra_key, [])
    existing_text = "\n".join(f"- {t}" for t in existing)
    prompt = (
        f"Generate 4 more gotcha topics for the '{category}' domain of the Claude Certified Architect Foundations exam. "
        f"These must be DIFFERENT from the ones already listed below. "
        f"Return ONLY a plain numbered list (1. ... 2. ... 3. ... 4. ...) with no extra explanation.\n\n"
        f"Already covered:\n{existing_text}"
    )
    with st.spinner("Generating new gotchas..."):
        raw = get_claude_response(prompt, system_prompt=SYSTEM_PROMPT_GOTCHA)

    new_topics = []
    for line in raw.strip().splitlines():
        line = line.strip()
        if line and line[0].isdigit():
            parts = line.split(". ", 1)
            if len(parts) == 2:
                new_topics.append(parts[1].strip())
    if new_topics:
        st.session_state[extra_key] = st.session_state.get(extra_key, []) + new_topics
        st.rerun()

st.divider()

st.subheader("Ask Claude anything about this category")
st.caption(f"Ask any question related to: {category}")

user_question = st.text_area(
    "Your question",
    placeholder="e.g. What's the difference between cache writes and cache reads in terms of pricing?",
    key=f"freetext_{category}",
    label_visibility="collapsed",
)

if st.button("Ask Claude", key=f"ask_{category}", type="primary"):
    if not user_question.strip():
        st.warning("Please enter a question first.")
    else:
        system = f"{SYSTEM_PROMPT_GOTCHA}\n\nThe user is asking about the category: {category}."
        st.markdown("**Claude's answer:**")

        response_placeholder = st.empty()
        full_response = ""

        with st.spinner("Thinking..."):
            stream_ctx = get_claude_response(user_question, system_prompt=system, stream=True)

        with stream_ctx as stream:
            for text in stream.text_stream:
                full_response += text
                response_placeholder.markdown(full_response + "▌")
        response_placeholder.markdown(full_response)
